theme: jekyll-theme-minimal
title: Chuanqi Zang
subtitle: 臧传祺
# description: Ismail CELEN's CV
# Email: jnchuanqizang@gmail.com
# title: [Chuanqi Zang (臧传祺)]
description: |[
Ph.D. Student |
MCISLAB | 
the School of Computer Science and Technology | 
Beijing Institute of Technology (BIT)
Address: No. 5, South Street, Zhongguancun, Haidian District, Beijing, China
Email: jnchuanqizang@gmail.com]

logo: [https://raw.githubusercontent.com/Chuanqi-Zang/Chuanqi-Zang.github.io/master/CQ.jpg]
