theme: jekyll-theme-minimal
title: [Chuanqi Zang (臧传祺)]
description: [
Ph.D. Student
MCISLAB
the School of Computer Science and Technology 
Beijing Institute of Technology (BIT)
Address: No. 5, South Street, Zhongguancun, Haidian District, Beijing, China
Email: jnchuanqizang@gmail.com]
